OPERATOR = {'BARABAR':'='}
NUMBERS = {'YAK':1 , 'DOH':2 , 'SAY':3 , 'CHAAR':4 , 'PUNCH':5 , 'SASH':6 , 'HAFTH':7 , 'HASHTH' :8, 'NOH':9  , 'SEPOR':0,'DAH':10,'YAZDAH':11 , 'DOWAZDAH':12 , 'SEIZDAH':13 , 'CHAARDAH':14 , 'PAANZDAH':15 , 'SAAZDAH':16 , 'HABDAH':17 , 'HASHDAH' :18, 'NOOZDAH':19  , 'BEESTH':20}
# print(NUMBERS)
ARETHMATIC = {'JAMA':'+' , 'KASH' :'-', 'TAKSEEM' :'/', 'ZARBE':'*'}
LPAREN = '('
RPAREN = ')'